added dto, controller, mapper
mmosii/online-book-store pull request #2
Opened 2023-10-15 21:20 UTC by mmosii

2023-10-15 22:23 UTC, don-bigdad approved these changes

2023-10-15 22:23 UTC, don-bigdad commented on src/main/java/mmosii/bookstore/controller/BookController.java
> +@RequestMapping(value = "/books")
in task(Book Endpoints:
GET: /api/books (Retrieve book catalog))

2023-10-16 08:57 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-10-16 08:57 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/config/MapperConfig.java
> +public class MapperConfig {
it is better to specify @MapperConfig directly on a mapper class

2023-10-16 08:57 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/dto/BookDto.java
> +public class BookDto {
is it possible to use record for DTO?

2023-10-16 08:57 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/mapper/BookMapper.java
> +    Book fromDto(CreateBookRequestDto requestDto);
`toBook` sounds better :)

2023-10-16 08:57 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/repository/impl/BookRepositoryImpl.java
> +            return Optional.ofNullable(book);
you can inline this :)

2023-10-16 08:57 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(book);
you can do this via single Optional methods chain

don't forget that Optional has a `map` method :)

2023-10-16 09:22 UTC, mmosii commented on src/main/java/mmosii/bookstore/dto/BookDto.java
> +public class BookDto {
Application works good with record but have problem with maven checkstyle.  " unexpected token: record "

2023-10-16 10:26 UTC, liliia-ponomarenko approved these changes
Great 😊

2023-10-16 10:27 UTC, merged