added validation to CreateBookRequestDto, added CustomGlobalException…
mmosii/online-book-store pull request #4
Opened 2023-10-17 16:08 UTC by mmosii

…Handler

2023-10-17 18:07 UTC, don-bigdad approved these changes

2023-10-17 18:07 UTC, don-bigdad commented on src/main/java/mmosii/bookstore/dto/CreateBookRequestDto.java
>  public class CreateBookRequestDto {
this class also can be record

2023-10-19 00:34 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-10-19 00:34 UTC, NazarSmith228 commented on pom.xml
> +        </dependency>
it is better to use `spring-boot-starter-validation`

2023-10-19 00:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/controller/BookController.java
> +    public BookDto updateBook(@PathVariable Long id,
just FYI

you may also validate such things as @PathVariable, @RequestParams etc. It looks like:
```
@PathVariable @Positive Long id
```

In order to be able to perform such validation you need to annotate your controller class with @Validated annotation

again, this is just FYI - apply it or not :)

2023-10-19 00:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/dto/BookDto.java
> +                      BigDecimal price, String description, String coverImage) {
usually fields of records are formatted as follows:
```
public record BookDto(Long id, 
                      String title, 
                      String author, 
                      String isbn,
                      BigDecimal price, 
                      String description, 
                      String coverImage) {
```

2023-10-19 00:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/dto/CreateBookRequestDto.java
>  public class CreateBookRequestDto {
why not record?

2023-10-19 00:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/dto/CreateBookRequestDto.java
> +    @NotNull
it is better to use `@NotBlank` with strings

2023-10-19 00:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/dto/CreateBookRequestDto.java
> +    @Min(0)
`@Min(0)` looks weird :)

could you use `@Positive` or `@PositiveOrZero`?

2023-10-19 00:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
time is pretty useless in response body - it does not bring any value to the client

status is obvious as well - no sense to have it in body

2023-10-19 00:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/exception/CustomGlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleMethodArgumentNotValid(
do you have any other exceptions except for `MethodArgumentNotValidException`?

does it make sense to handle them as well?

2023-10-20 09:32 UTC, liliia-ponomarenko approved these changes
Great!

2023-10-20 10:04 UTC, merged