implemented User and Role models, security
mmosii/online-book-store pull request #6
Opened 2023-10-25 13:44 UTC by mmosii

2023-10-25 20:09 UTC, teract10s approved these changes
LGTM. I don't know what can i add

2023-10-27 08:18 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments.

2023-10-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mmosii/bookstore/repository/user/RoleRepository.java
> +    Role findAllByName(RoleName name);
It's better findRoleByName or getRoleByName

2023-10-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mmosii/bookstore/security/CustomUserDetailsService.java
> +                -> new UsernameNotFoundException("Can't find user"));
Also, you can add username 
"Can't find user by username: " + username

2023-10-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mmosii/bookstore/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
it's better authorizationHeader by meaning

2023-10-27 14:39 UTC, Andriy-dz approved these changes

2023-10-27 14:43 UTC, merged