implemented Order, OrderItem
mmosii/online-book-store pull request #9
Opened 2023-11-08 15:56 UTC by mmosii

2023-11-08 17:04 UTC, Oleksandr-Tymoshenko requested changes
Good job, lets make it better

2023-11-08 17:04 UTC, Oleksandr-Tymoshenko commented on src/main/java/mmosii/bookstore/service/impl/OrderServiceImpl.java
> +        order.setShippingAddress(requestDto.shippingAddress());
advice you to make a separate method for this

2023-11-08 17:04 UTC, Oleksandr-Tymoshenko commented on src/main/java/mmosii/bookstore/service/impl/OrderServiceImpl.java
> +        }
you go through cart items 2 times. You can calculate total price in second cycle and set it to order like:

newOrder.setTotal(total.add(orderItem.getPrice()).add(newOrder.getTotal()));

and on line 57 setTotal(BigDecimal.ZERO) to avoid exception

if you use transactional, total will be updated in the database without calling save method 


**Also advice you to make mapper from CartItem to OrderItem to reduce code size**

2023-11-08 17:04 UTC, Oleksandr-Tymoshenko commented on src/main/java/mmosii/bookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(orderRepository.save(order));
if you use transactional i think it is not necessarily to save order because it is already in persistent context.

2023-11-08 17:04 UTC, Oleksandr-Tymoshenko commented on src/main/java/mmosii/bookstore/service/impl/OrderServiceImpl.java
> +    public OrderItemDto getOrderItemById(Long orderId, Long id) {
Can user find information from someone else's order?

2023-11-08 17:04 UTC, Oleksandr-Tymoshenko commented on src/main/java/mmosii/bookstore/service/impl/OrderServiceImpl.java
> +    public List<OrderItemDto> getOrderItemsByOrder(Long id) {
Can user find information from someone else's order?

2023-11-08 17:04 UTC, Oleksandr-Tymoshenko commented on src/main/java/mmosii/bookstore/model/Order.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```
and add EntityGraph to order repository

Eager adds one more select query

2023-11-10 16:19 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-10 16:19 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/model/Order.java
> +    @ManyToOne(fetch = FetchType.LAZY)
pls add `optional = false` since order can't exist without user

2023-11-10 16:19 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/model/Order.java
> +    @OneToMany(mappedBy = "order")
how about cascades and orphanRemoval?

2023-11-10 16:19 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/model/OrderItem.java
> +    private Book book;
pls make sure that you are able to delete book properly (i.e. order items should be deleted automatically)

2023-11-10 16:19 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/service/impl/OrderServiceImpl.java
> +            orderItem.setPrice(orderItem.getBook().getPrice());
this seems to be a job for mapper

2023-11-10 16:19 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(orderRepository.save(order));
there is no need to call `save` since you have an active session

and please verify that `getReference` here doesn't break mapper logic

2023-11-13 09:34 UTC, NazarSmith228 approved these changes
LGTM, but pls pay attention to my remarks

2023-11-13 09:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/model/Order.java
> +    @OneToMany(mappedBy = "order", cascade = CascadeType.REMOVE, orphanRemoval = true)
I would change the cascade to `ALL` since order item is completely bound to order

2023-11-13 09:34 UTC, NazarSmith228 commented on src/main/java/mmosii/bookstore/service/impl/OrderServiceImpl.java
> +        }
this can be extracted into a separate method to simplify the current one

2023-11-13 10:13 UTC, merged